server {
listen 80;
server_name retrochat.my.id;

```
gzip on;
gzip_types text/plain text/css application/json application/javascript;
gzip_min_length 1000;

location /assets/ {
    alias /var/www/cv-generator/cv-generator/frontend/dist/assets/;
    expires 30d;
    add_header Cache-Control "public, immutable";
}

location / {
    root /var/www/cv-generator/cv-generator/frontend/dist;
    try_files $uri $uri/ /index.html;
}

location /api/ {
    proxy_pass http://127.0.0.1:3001;
    proxy_http_version 1.1;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;

    proxy_read_timeout 60s;
    proxy_send_timeout 60s;

    client_max_body_size 5M;
}
```

}

